### PR TITLE
changes for other browsers

### PR DESCRIPTION
**Pull request by alanbuxey**
hi,

as per email from a little while back - here are changes that allow the webextension to operate in other browsers. loads with no error on chrome, opera and Firefox nightly

### CODE REVIEW

**Comment by khlr** [comment]
Hello @alanbuxey !

Thank you very much for this pull request 👍 

Did you debug your changes? SAML-tracer starts in Chrome, but it doesn't trace any requests. 
Fortunately it's no big deal 😊 There's just another `var browser = browser || chrome` required in SAMLTrace.js.

How to proceed? I'm going to merge your pull request into my fork and put some other small things on top of that. Then I'll take the result and create a pull request in the original SAML-tracer repo. This way, your changes will hopefully be integrated into the "real" SAML-tracer quite soon 😃 Is this ok for you?

**Comment by alanbuxey** [comment]
hi,

you could probably just get away with ONLY having the "var browser =
browser || chome" in SAMLTrace.js ?  I'll have a check.

as for proceeding, yes - sounds like a plan. more interesting will be when
this is available for people directly from store for
their browsers without having to mess with in the extension area with
importing uncompressed files or xpinstall flags :)

alan

**Comment by khlr** [comment]
No, there'll be two inserations necessary. But anyways 😉

I think I'll have some time this evening to adjust this. Then I'll create the pull request to the main repo. And yes, the extension could then be available to user right from the regular store pretty soon 😊

**Comment by alanbuxey** [comment]
okay..made the change here - interestingly, neither opera nor chrome are
showing the correct window contents (they did back in last year when i
submitted same patches..) - the window
doesnt show the seperator not the updates..... however it IS working - the
"xxx requests received (yyy hidden)" at the bottom updates and export
provides a nice .json file filled with the data.
that'll need looking into

alan

**Comment by khlr** [comment]
> the window doesnt show the seperator not the updates

That's just a minor thing to adjust in the Splitter.js. I'll fix that.
Thank you for this PR again :-)

**Comment by khlr** [comment]
@alanbuxey, fyi: Here's the PR to the original repo: https://github.com/UNINETT/SAML-tracer/pull/45

**Pull request merged**
