### PR TITLE
only firefox takes browser. all the others take chrome

### PR DESCRIPTION
**Pull request by alanbuxey**
tested with various browsers

### CODE REVIEW

**Comment by khlr** [comment]
Hello Alan!

Thank you for your pull requests! 

You're absolutely right, since SAML tracer is being converted to a Web Extension it's a great opportunity to make this tool available to browsers, too. I had this in mind as well, but not yet.
Let me explain why: Right now I'm still converting the existing extension (see my [pull request](https://github.com/UNINETT/SAML-tracer/pull/23) to the original repo). There are still some features missing (which might be implemented with subsequent pull requests), but even worse, there are also some fundamental things not yet in place (see Thijs' [comment and below](https://github.com/UNINETT/SAML-tracer/pull/23#issuecomment-344970423)).

I think it'd be a good idea to first finish the actual conversion and add additional features afterwards. I wouldn't mix these two topics (which I'd do if I merged your pull request into mine). Despite the code changes are really minimalistic, I think it's still a big deal to support multiple browsers, and for clarity's sake this should come in it's own pull request back to the Uninett repo.

I hope I have expressed myself in a reasonably understandable way :-)

**Comment by alanbuxey** [comment]
yes, okay - we can keep a separate branch for the 'working on multiple
browser' - the good news is that right now (with those minimal changes)
the current stuff does indeed work the same on Chrome and Opera....which is
great. just need to be aware of the Firefox oddities.

first priority is that the extension works in Firefox as it used to
second is that it works, using Web Ext API on all the browsers...no more
different plugins needed, just the one resource

alan

**Comment by khlr** [comment]
Hi Alan!

Sorry, I'm afraid I accidentally deleted the branch associated to your pull request. Could you please submit it again?

**Comment by khlr** [comment]
Hi Alan!

Sorry, I'm afraid I accidentally deleted the branch associated to your pull request. Could you please submit it again?

**Comment by khlr** [comment]
@alanbuxey may I ping you again? ;-)

**Comment by alanbuxey** [comment]
ping received - sorry for the delay - I've been busy with other things.
 sure, I'll get a commit over to you again - I believe this is just the
basic things required to get
SAML-tracer working under other browsers - it was only a few lines here and
there.

alan

**Comment by khlr** [comment]
Never mind :) sorry for the delay that _I_ put in this.

**Comment by alanbuxey** [comment]
hi,

had some spare time so made some new commits and sent a pull request to
your repo.

cheers

alan

**Pull request closed without merging**
